spring:
  application:
    name: FarmDataCollector
  datasource:
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  mvc:
    view:
#      prefix: /templates
      suffix: .html